# draw mode 
# seg: 3d bbox + BEV segmentationMap, 
# vec: 3d bbox + VectorMap, 
# 2d: 2d bbox, 
# 3d: 3d bbox
draw_mode: "3d"

# ip configuration
ip: "localhost"
port: 65432

# material image paths
mat_dict:
    left: "src/imgs/green_arrow_left.png"
    right: "src/imgs/green_arrow_right.png"
    left_dark: "src/imgs/green_arrow_left_dark.png"
    right_dark: "src/imgs/green_arrow_right_dark.png"
    spd_limit_60: "src/imgs/spd_limit_60.png"
    